### PR TITLE
Adding API-version to document title

### PR DESCRIPTION
**Pull request by MollieRick**
See issue #127

### CODE REVIEW

**Comment by willemstuursma** [comment]
This looks good to me! `versionName` is always set.

**Comment by willemstuursma** [comment]
Maybe `Create payment — Mollie v1 API documentation` would be even better.

**Comment by willemstuursma** [comment]
@ndijkstra what do you think?

**Comment by ndijkstra** [comment]
@willemstuursma I like your suggestion `Create payment — Mollie v1 API documentation`

**Comment by MollieRick** [comment]
@willemstuursma @ndijkstra How about `Create payment - Mollie API v1 documentation`? It is version 1 of the API, not Mollie :-)

**Comment by vernondegoede** [comment]
I don't have access to my laptop right now, but how does this look for guides? We don't want to set an API version number for these pages.

**Comment by MollieRick** [comment]
@willemstuursma @vernondegoede Done. Please check again

**Comment by mvdpanne** [comment]
Seems fine to me? Not sure what you mean with magic strings but I'd say lets merge it.

**Comment by vernondegoede** [comment]
LGTM 🚢 it

**Pull request merged**
