### PR TITLE
APM-944 Add interval to update subscription API

### PR DESCRIPTION
**Pull request by ndijkstra**

### CODE REVIEW

**Comment by sandervanhooft** [comment]
https://github.com/mollie/mollie-api-php/pull/435

**Comment by sandervanhooft** [comment]
Just to be sure: will sending an unchanged interval NOT trigger an exception?

**Comment by ndijkstra** [comment]
> Just to be sure: will sending an unchanged interval NOT trigger an exception?

No, this should not be a problem

**Comment by sandervanhooft** [comment]
Great @ndijkstra !

**Pull request merged**
