### PR TITLE
Update security.rst

### PR DESCRIPTION
**Pull request by arnetm**
TLS 1.0/1 deprecation requires clarification on TLS.

### CODE REVIEW

**Review by vernondegoede — APPROVED** [review]

**Review by jasperkennis — APPROVED** [review]

**Comment by sandervanhooft** [comment]
What happens if an outdated TLS is used? Asking so I can recognize the issue when providing support.

**Comment by arnetm** [comment]
@sandervanhooft Connection to api.molle.com or www.mollie.com will be impossible. A network error will be thrown.

**Comment by sandervanhooft** [comment]
Gotcha, thanks!

**Comment by MollieRick** [comment]
In effect, merging.

**Pull request merged**
