### PR TITLE
PROC-1227 Add new method params to docs

### PR DESCRIPTION
**Pull request by Smitsel**

### CODE REVIEW

**Comment by Smitsel** [comment]
The `billingEmail` is going to be used for Slice it in the future.
Should we keep the description like this, or maybe add that info already?

**Comment by willemstuursma** [comment]
> Should we keep the description like this, or maybe add that info already?

This is fine.

Sorry I committed with the message _Typo_ but that's a mistake, it was an elaboration.

**Comment by willemstuursma** [comment]
@sandervanhooft fyi

**Comment by willemstuursma** [comment]
@davdebcom fyi

**Pull request merged**
