### PR TITLE
Merge 'Hosted Onboarding' in to Mollie Connect documentation.

### PR DESCRIPTION
**Pull request by arnetm**
It makes no sense to have https://docs.mollie.com/onboarding/getting-started and https://docs.mollie.com/oauth/onboarding. Both are used in 'Connect'. Merge will make the functionalities of Connect more clear and one page can talk about both functionalities and flows.

### CODE REVIEW

**Comment by mattijsbliek** [comment]
We should make sure the old page has a proper redirect to the new page.

**Comment by mattijsbliek** [comment]
@actuallymab Would you mind taking this review?

**Review by actuallymab — CHANGES_REQUESTED** [review]
Thanks for the improvement and it looks good to me, however I have two minor things:
* Can you please add the redirect rule to `origin-response.js` file?
* Also please do not forget to update `source/theme/sidebar-guides.html` and remove the menu item for the deleted page.

**Comment by actuallymab** [comment]
Closing this PR, because I moved changes to a new PR: https://github.com/mollie/api-documentation/pull/726

**Pull request closed without merging**
