### PR TITLE
Add newly available locales for the payment screen

### PR DESCRIPTION
**Pull request by dabroek**

### CODE REVIEW

**Comment by ndijkstra** [comment]
The locales are also on this pages: 
- https://docs.mollie.com/reference/v2/customers-api/create-customer
- https://docs.mollie.com/reference/v2/methods-api/list-methods

**Comment by willemstuursma** [comment]
Are there also variants created for the v1 API?

**Comment by willemstuursma** [comment]
Please add it to the changelog too (in that branch).

**Comment by dabroek** [comment]
@ndijkstra The locales for the `list-methods` endpoint differ from the ones in the `payments` and `customer` endpoints.

**Comment by dmvdbrugge** [comment]
I think that while the `list-methods` locales serve a semi-different purpose, the locales can be added there as well. There won't have been done any sorting, but the methods will have been translated.

**Comment by ndijkstra** [comment]
no_NO should be nb_NO: 
https://github.com/TakahikoKawasaki/nv-i18n/issues/9
https://github.com/fzaninotto/Faker/issues/854

**Comment by dmvdbrugge** [comment]
@ndijkstra that's an internal discussion I think. As it stands, Mollie accepts no_NO, so to note otherwise in the documentation is just plain wrong.

**Comment by dabroek** [comment]
@ndijkstra Thank you for bringing this to our attention. I've replaced the invalid `no_NO` with `nb_NO`.

**Comment by dabroek** [comment]
@dmvdbrugge I've added the new locales to the list-methods endpoint to allow the payment methods to be translated and ordered by relevance.

**Pull request merged**
