### PR TITLE
PROC-1306 - Find a good place on docs.mollie.com for our Reseller API

### PR DESCRIPTION
**Pull request by MollieRick**

### CODE REVIEW

**Comment by willemstuursma** [comment]
Downloads can be moved to the Overview. 

It looks good to me. @vernondegoede what do you think?

Obviously, it can use a review and some polishing up.

**Comment by vernondegoede** [comment]
@MollieRick Nice work 💪

I noticed something (unrelated) to this PR though: switching versions doesn't seem to work when you're in the Mollie Connect / Reseller API **Reference** docs. If the page does not exist using a v2 URL parameter, we could link to https://docs.mollie.com/reference/v2 or https://docs.mollie.com/reference/v1 (we recently added redirects from these URLs to the first article).

**Comment by MollieRick** [comment]
@vernondegoede All endpoints are now into the docs. Can you check all text please? Some of them are very old and maybe not in the way how we want to communicate.

**Comment by willemstuursma** [comment]
@MollieRick I'll review the wording.

**Comment by willemstuursma** [comment]
`:doc:`obligatory parameters </reseller-api/secret-keys>``: this should use a `:ref:` so that it can link to the right header.

**Comment by willemstuursma** [comment]
You should also proofread it yourself @MollieRick.

**Pull request merged**
