### PR TITLE
PROC-1316 Update webhook and redirect urls

### PR DESCRIPTION
**Pull request by willemstuursma**
@sandervanhooft

### CODE REVIEW

**Comment by sandervanhooft** [comment]
👍 Looks good to me

**Comment by Smitsel** [comment]
Why do we add `required` to GET responses?
Should these not be `null`? Because we don't `require` anything on a get response right?

**Comment by sandervanhooft** [comment]
Yes, that `required` label has been confusing to me as well. Perhaps inverse it with an `optional` label for responses?

**Comment by willemstuursma** [comment]
Its a bit tricky in the source yes, `:required: false` causes the text _Optional_ to appear.

**Comment by willemstuursma** [comment]
@mvdpanne ☝️

**Comment by willemstuursma** [comment]
@Smitsel @sandervanhooft there is a (subtle) difference between a key is optional and a key can be `null`.

**Comment by willemstuursma** [comment]
@mvdpanne yeah it's fine for now

**Pull request merged**
