### PR TITLE
Add info about webhook retries to the Create Payment Links page

### PR DESCRIPTION
**Pull request by ArtemGordinsky**
Adding some info about webhook retries to the page about [Creating Payment Links](https://docs.mollie.com/reference/v2/payment-links-api/create-payment-link) (the green "Note" block)

Screen Shot 2022-04-08 at 16 39 19

### CODE REVIEW

**Comment by mollierobbert** [comment]
Can you also update `webhooks.rst` with a section about payment links?

**Comment by willemstuursma** [comment]
Sorry please hold merging for now.

**Comment by ArtemGordinsky** [comment]
@mollierobbert @willemstuursma Hey gents,
I've updated the docs as requested, please let me know what you think.

I'm still calling the retry scheme "exponential back-off" even though, being limited to 1h interval, it's not _really_ exponential, as @willemstuursma already pointed out. Not sure how else to call it.

**Comment by ArtemGordinsky** [comment]
Removed the details on "exponential back-off" and the 100 retries to avoid any confusion after chatting with @mollierobbert.

**Comment by mollierobbert** [comment]
I think this is good enough now, @willemstuursma. Artem removed the wording of the exact retry schema differences, instead focusing just on documenting that payment link webhooks exist.

**Comment by willemstuursma** [comment]
Thanks all 👋

**Pull request merged**
