### PR TITLE
Revert "Use separate CDN to serve assets"

### PR DESCRIPTION
**Pull request by hvalle**
Reverts mollie/api-documentation#161

We need to fix CSP so assets load.

### CODE REVIEW

**Comment by martijnpolder** [comment]
Could you explain what you mean? The CSP in the assets CF behaviour is a copy of the current docs CSP, so no change in behaviour is expected until we start tweaking the CSPs.

**Comment by hvalle** [comment]
Current CSP is:

`content-security-policy: default-src 'self'; img-src 'self' data: https://images.ctfassets.net; font-src 'self' https://cdn.mollie.com; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.mxpnl.com https://tagmanager.google.com 'sha256-FPgvfx+DeiJzmOHcDk2Iig1vKX6j8I0pKqPA7y33Xbc=' 'sha256-dSca7Fq9h/m8NPfsEIGN6QsOnwspkqCSOGFBGND+lps=' 'sha256-0M7Y8vfoB3jQRWrbd9UeLZorU2w32qynoWspDQn7U0g=' 'sha256-akWsBON1KU9NUSFengZbPuVOt+8KK3uSXcBP5Hc0sqQ=' 'sha256-nST9yaMPaU/xAS62+YWnvg5TxAXYYQm1Fn5Ybpu0AXM=' 'sha256-q/CGewBJOc0HL8ZusH9Fqnh2aZgLOH7lBvepoEVOrVw='; style-src 'self' 'sha256-biLFinpqYMtWHmXfkA1BPeCY0/fNt46SAZ+BBk5YUog='; object-src 'self'; media-src 'none'; form-action 'none'; connect-src https://www.google-analytics.com https://api.mixpanel.com; report-uri https://mollie.report-uri.com/r/d/csp/enforce`

We need to allow https://assets.docs.mollie.com/ into that CSP.

**Comment by martijnpolder** [comment]
I'll add it

**Comment by hvalle** [comment]
Thanks! Let me know when it's done so I can re-revert the PR 👍

**Pull request merged**
