### PR TITLE
Order response fixes

### PR DESCRIPTION
**Pull request by ndijkstra**

### CODE REVIEW

**Comment by sandervanhooft** [comment]
@ndijkstra 

#153 is probably relevant here.

**Comment by sandervanhooft** [comment]
@ndijkstra Shouldn't the `method` be included in the Order.get response?

**Comment by sandervanhooft** [comment]
Same for `locale`

**Comment by sandervanhooft** [comment]
And `orderNumber`

**Comment by sandervanhooft** [comment]
From the docs:
> Creating an order will automatically create the required payment to allow your customer to pay for the order.

So the `method`, `locale`, `webhookUrl` and `redirectUrl` fields seem to relate to the `Payment` resource that's created(?). Should there be a `paymentId` or complete payment resource included in the response? Is there another way to retrieve the payment?

(Obviously the `checkout` link can be used for finishing the payment, but that's not for retrieving the related payment(s)).

**Comment by willemstuursma** [comment]
@sandervanhooft eventually we'll provide an `/v2/orders/ord_xxx/payments` endpoint.

**Comment by ndijkstra** [comment]
Thanks @sandervanhooft I will add them

**Comment by willemstuursma** [comment]
Thanks @ndijkstra

**Pull request merged**
